os: Windows Server 2012
install:
  - "SET PYTHON=C:\\Miniconda3-x64"
  - "SET LIBRARY=%PYTHON%\\Library"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - conda install -c omnia --yes --quiet mingwpy bzip2 zlib
  - "SET CFLAGS=-IC:\\Miniconda3-x64\\Library\\include"
  - "SET CXXFLAGS=-IC:\\Miniconda3-x64\\Library\\include"
  - bash configure -noarpack -nomathlib -nonetcdf
  - make

build: false
