os: Windows Server 2012
install:
  - "SET PYTHON=C:\\Miniconda3-x64"
  - "SET LIBRARY=%PYTHON%\\Library"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - conda install -c omnia --yes --quiet mingwpy bzip2 zlib
  - "copy %LIBRARY%\\lib\\libbz2.lib %LIBRARY%\\lib\\libbz2.a"

  - "SET CXXFLAGS=-IC:\\Miniconda3-x64\\Library\\include"
  - "SET LDFLAGS=-LC:\\Miniconda3-x64\\Library\\lib"
  - "SET CFLAGS=%CXXFLAGS%"
  - bash configure -noarpack -nomathlib -nonetcdf
  - make

build: false
