os: Windows Server 2012
install:
  - "SET PYTHON=C:\\Miniconda3-x64"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - conda install -c omnia --yes --quiet mingwpy bzip2 zlib
  - bash configure -noarpack -nomathlib -nonetcdf gnu
  - make

build: false
